@url=http://localhost:3000/api
@accessToken={{login.response.body.$.data.accessToken}}

### Register
POST {{url}}/auth/register
Content-Type: application/json

{
    "email": "test12@mail.com",
    "password": "password",
    "firstName": "test1",
    "lastName": "test1"
}

### Login
# @name login
POST {{url}}/auth/login
Content-Type: application/json

{
    "email": "test2@mail.com",
    "password": "password"
}


### Get Me
GET {{url}}/auth/me
Content-Type: application/json
Authorization: Bearer {{accessToken}}


### Update User
POST {{url}}/users
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "firstName": "Firstname updated 1",
    "lastName": "lastName updated",
    "email": "test100@mail.com"
}


### Get Dashboard
GET {{url}}/users/dashboard
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### Get Achievements
GET http://localhost:3000/api/achievements
Content-Type: application/json
Authorization: Bearer {{accessToken}}
